# RPC 服务监听地址
rpcserverip=127.0.0.1
rpcserverport=8000

# ZooKeeper 地址
zookeeperip=127.0.0.1
zookeeperport=2181

# 日志输出目录（相对于程序启动目录）
log_path=./log/
log_prefix=coroutine_rpc
log_max_file_size=5
log_enable=true
rpc_log_level=DEBUG
app_log_level=DEBUG
log_sync_interval=500
